### ISSUE TITLE
Pools support

### ISSUE THREAD

**Issue by dimorinny** [matt-richardson/TeamCityAgentAutoRegisterPlugin#2]
Hi, is it possible to associate auth token and teamcity agents pool?
I have tried to use original teamcity plugin for it, but I didn't understand why I should use unique token for every agent.

**Comment by matt-richardson** [comment]
There is currently no support in this plugin for assigning a pool, though PR's are appreciated.

That said, I think you can use the original  [Agent Custom Token Authorize Plugin](https://confluence.jetbrains.com/display/TW/Agent+Custom+Token+Authorize+Plugin) with something like:

```
agent.authorize.tokens=TokenForDefaultAgentsPool:70d44d1e5007dd6b:99999:0,TokenForPoolWithId12:96ab7cfe7547ca:99999:12
```

With this configuration, any agent that has `teamcity.magic.authorizationToken=70d44d1e5007dd6b` will end up in the `Default Agents Pool`, and any with `teamcity.magic.authorizationToken=96ab7cfe7547ca` will end up in the agent pool with id 12. It will work for the first 99999 agents for each token, which hopefully should be enough :)

Hope that helps!

**Comment by dimorinny** [comment]
@matt-richardson, I have tried to use it, but as described, it doesn't support agents limit more than 1. In my case it has no effect when there is agent in pool.

**Comment by matt-richardson** [comment]
Ahh, in that case, your best bet is to take it up with JetBrains - unless you fancy writing a PR :)

**Comment by Dmitriusan** [comment]
I can confirm that setting the limit at the property `agent.authorize.tokens` does not help - only one agent can register with each token
